packages:
  - "packages/*"
  - "apps/*"

catalog:
  typescript: ^5.3.0

catalogs:
  repo:
    eslint: ^8.50.0
    prettier: ^3.0.0
  types:
    "@types/node": ^20.0.0
    "@types/react": ^18.2.0
  ui:
    react: ^18.2.0
